[package]
name = "pptx-engineer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.5", features = ["derive"] }
quick-xml = { version = "0.41.0" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
thiserror = "2.0.19"
zip = { version = "8.6.0", features = ["deflate"] }
